### ISSUE TITLE
[WIP] H8 boot-mode flashing: programmer software

### ISSUE THREAD

**Issue by Hurricos** [Hurricos/insight_fw_RE#2]
Platform: Designed around an Arduino Nano

Requirements:

(original diagram)
![image](https://github.com/user-attachments/assets/7c10c7fe-4354-45d9-9b5e-188b2e6256a5)

- AltSoftSerial - Baud rate among 2400, 4800, 9600 required - see https://www.insightcentral.net/posts/1534468/
  - https://www.pjrc.com/teensy/td_libs_AltSoftSerial.html
  - TX: D9
  - RX: D8
- Hardware serial
- GPIO
  - VPP: A0
  - MD2: A0
  - VCC: A5
  - LAT: A1
  
### TODOs
- [x] Find the Arduino sketch used last year for this.
- [ ] Adjust sketch
  - [ ] AltSoftSerial
  - [x] Separate top-level .h
  - [x] Separate cpu_map.h
  - [ ] Separate serial interface
