### ISSUE TITLE
Rewrite Insight MCM

### ISSUE THREAD

**Issue by Hurricos** [Hurricos/insight_fw_RE#3]
### TODOs
- [ ] Programmer module software
  - #2.
  - Manipulates MD0/MD1/MD2/reset/VPP/VCC pins as needed to put the chip into Boot Mode.
- [ ] Programmer module hardware
  - informed by #2.
- [ ] H8 boot-mode firmware
  - #1.
- [ ] Host-side program
  - Very simple: most of the work is done by firmware in #2.
  - Prototype in .sh.
